#**1 Introduccion**

En el siguiente cuaderno se realizara el producto entre dos matrices cuadradas, el resultado del producto es una nueva matriz. Es decir:

<center>$\ MR= A x B =A (a(11)...a(1n)) *B(b(11)...b(1n)) = (a(11)b(11)+ ... +a(1n)b(1n))$</center>

Si bien el producto entre matrices tienen la propiedad de que el número de columnas de la matriz A tiene que ser igual al número de filas de la matriz B, en este ejercicio se opto por realizar el producto solo para matrices cuadradas.


#**2 Armando el ambiente**

No son necesarios, ejecuciones previas del armado del ambiente

#**3 Desarrollo**

In [ ]:
# -----------------------------------------------------------
#@title 3.1 Parámetros de ejecución { vertical-output: true }

f= 3#@param {type: "number"}
c= 3#@param {type: "number"}

# ------------------------------------------------------------

import numpy

# CPU - Defino la memoria de la matriz en cpu.
matriz1 = numpy.random.random((f,c)) *10
matriz1= matriz1.astype(numpy.int32())

matriz2 = numpy.random.random((f,c)) *10
matriz2 = matriz2.astype(numpy.int32())

matriz_r = numpy.zeros(shape=(f,c))
matriz_r = matriz_r.astype(numpy.int32())

for i in range(0,c):
  for j in range(0,f):
    for k in range(0,c):
      matriz_r[i][j] += matriz1[i][k] * matriz2[k][j]

print("Primer matriz")
print(matriz1)
print("Segunda Matriz")
print(matriz2)
print("Matriz Resultado")
print(matriz_r)

Primer matriz
[[4 5 7]
 [3 8 0]
 [2 3 9]]
Segunda Matriz
[[9 0 9]
 [0 7 9]
 [8 0 2]]
Matriz Resultado
[[92 35 95]
 [27 56 99]
 [90 21 63]]


#**4 Tabla de Pasos**
Procesador | Funciòn | Detalle
------------|---------|----------
CPU      |  @param                | Lectura del tamaño de las matrices en Colab.
CPU      |  import                | Importa los módulos para funcionar.
CPU      |  numpy.random.randn( (f,c) ) | Inicializa los Matrices.
CPU | for... | realizo el producto entre las matrices guardando el resultado en Matriz_r
CPU      |  print()               | Informo los resultados.

#**5 Conclusion**

Se puede observar en el codigo que el producto entre matrices en el CPU se realiza con ciclos anidados, dichas multiplicaciones y sumas están en una complejidad computacional[1] de O(N^3).

#**6 Bibliografia**

[1] Complejidad Computacional:[PDF](https://www.frlp.utn.edu.ar/materias/algoritmos/GUIACOMPLEJIDADDEALGORITMOS.pdf)